canonical_width = 512

[sprites."f-hang-corner"]
attachment = "point"
x = 368
y = 290

[sprites."f-lie"]
attachment = "line_y"
y = 179

[sprites."f-lie-sleep"]
attachment = "line_y"
y = 175

[sprites."f-sit"]
attachment = "line_y"
y = 269

[sprites."f-stand"]
attachment = "line_y"
y = 264

[sprites."s-hang-corner"]
attachment = "point"
x = 408
y = 254

[sprites."s-hang-wall-0"]
attachment = "line_x"
x = 135

[sprites."s-hang-wall-1"]
attachment = "line_x"
x = 153

[sprites."s-hang-wall-2"]
attachment = "line_x"
x = 136

[sprites."s-jump"]
attachment = "line_y"
y = 359

[sprites."s-lie"]
attachment = "line_y"
y = 189

[sprites."s-lie-sleep"]
attachment = "line_y"
y = 189

[sprites."s-peek-down"]
attachment = "line_y"
y = 196

[sprites."s-sit"]
attachment = "line_y"
y = 258

[sprites."s-stand"]
attachment = "line_y"
y = 254

[sprites."s-stand-close"]
attachment = "line_y"
y = 257

[sprites."s-stand-up"]
attachment = "line_y"
y = 283

[sprites."s-walk-0"]
attachment = "line_y"
y = 264

[sprites."s-walk-1"]
attachment = "line_y"
y = 268

[sprites."s-walk-2"]
attachment = "line_y"
y = 269
