#![cfg(target_os = "windows")]

//! Windows sprite asset loader.
//!
//! Loads PNG sprites with the `image` crate, scales them, converts to
//! pre-multiplied BGRA (required by `UpdateLayeredWindow`), and generates
//! horizontally-mirrored copies at load time.
//!
//! The `Anchor` type and `compute_anchor` logic are identical to the macOS
//! `assets.rs` so that `surface_to_screen_pos` in `windows.rs` can use the
//! same formulas as `surface_to_ns_origin` in `macos.rs`.

use std::cell::RefCell;
use std::collections::HashMap;
use std::path::Path;

use image::GenericImageView;

use crate::manifest::{Attachment, AnimationDef, Manifest, SurfaceConfig};

/// Upper bound (px) for a scaled sprite edge.  Guards against pathological
/// `canonical_width` / source-image sizes in untrusted `.pmate` manifests
/// that would otherwise drive a multi-gigabyte BGRA allocation.
const MAX_SPRITE_DIM: u32 = 8192;

// Sprites and manifest embedded at compile time (generated by build.rs).
pub(crate) mod embedded {
    include!(concat!(env!("OUT_DIR"), "/embedded_assets.rs"));
}

// ---- Anchor ----

/// Attachment point for a sprite, in scaled display pixels.
///
/// | attachment | anchor.x                             | anchor.y                             |
/// |------------|--------------------------------------|--------------------------------------|
/// | `line_y`   | 0 (unused)                           | distance from **bottom** to foot line |
/// | `line_x`   | distance from **left** to grip line  | 0 (unused)                           |
/// | `point`    | distance from **left** to attach pt  | distance from **bottom** to attach pt |
#[derive(Debug, Clone, Copy)]
pub struct Anchor {
    pub x: f64,
    pub y: f64,
}

// ---- Sprite ----

/// A loaded, scaled, pre-multiplied BGRA sprite ready for `UpdateLayeredWindow`.
pub struct Sprite {
    /// Row-major BGRA pixels, pre-multiplied alpha.
    pub bgra: Vec<u8>,
    pub w: i32,
    pub h: i32,
}

// ---- SpriteAssets ----

pub struct SpriteAssets {
    images:   HashMap<String, Sprite>,
    mirrored: HashMap<String, Sprite>,
    anchors:  HashMap<String, Anchor>,
    native: HashMap<String, (u32, u32, Vec<u8>)>,
    native_mirrored: HashMap<String, (u32, u32, Vec<u8>)>,
    cage: RefCell<HashMap<(String, bool, u32, u32, i16), (u32, u32, Vec<u8>, f64, f64)>>,
    pub canonical_width: f64,
    pub animations: HashMap<String, AnimationDef>,
    pub surfaces: SurfaceConfig,
}

impl SpriteAssets {
    /// Load every sprite listed in `manifest` from `char_dir/sprite/`.
    /// Returns `None` if any listed sprite is missing or unreadable.
    #[allow(dead_code)]
    pub fn load(char_dir: &Path, manifest: &Manifest, display_width: f64) -> Option<Self> {
        let scale = display_width / manifest.canonical_width.max(1.0);
        let sprite_dir = char_dir.join("sprite");

        let mut images   = HashMap::new();
        let mut mirrored = HashMap::new();
        let mut anchors  = HashMap::new();
        let mut native = HashMap::new();
        let mut native_mirrored = HashMap::new();

        for (name, info) in &manifest.sprites {
            // Reject names that could escape the sprite directory (groundwork
            // for untrusted `.pmate` manifests).
            if !crate::manifest::is_safe_asset_name(name) {
                eprintln!("[assets] rejecting unsafe sprite name: {name:?}");
                return None;
            }
            let path = sprite_dir.join(format!("{name}.png"));
            let img  = image::open(&path).ok()?;
            let (ow, oh) = img.dimensions();
            let native_rgba = img.to_rgba8().into_raw();
            let native_flip = mirror_rgba(&native_rgba, ow, oh);
            let nw = ((ow as f64 * scale).round() as u32).clamp(1, MAX_SPRITE_DIM);
            let nh = ((oh as f64 * scale).round() as u32).clamp(1, MAX_SPRITE_DIM);

            let scaled = img
                .resize_exact(nw, nh, image::imageops::FilterType::Triangle)
                .to_rgba8();

            let anchor = compute_anchor(info.x, info.y, oh as f64, scale, &info.attachment);
            let bgra   = rgba_to_bgra_premul(&scaled);
            let mirror = mirror_bgra(&bgra, nw as usize, nh as usize);

            native.insert(name.clone(), (ow, oh, native_rgba));
            native_mirrored.insert(name.clone(), (ow, oh, native_flip));
            images.insert(name.clone(),   Sprite { bgra,   w: nw as i32, h: nh as i32 });
            mirrored.insert(name.clone(), Sprite { bgra: mirror, w: nw as i32, h: nh as i32 });
            anchors.insert(name.clone(), anchor);
        }

        Some(SpriteAssets {
            images,
            mirrored,
            anchors,
            native,
            native_mirrored,
            cage: RefCell::new(HashMap::new()),
            canonical_width: manifest.canonical_width,
            animations: manifest.animations.clone(),
            surfaces: manifest.surfaces.clone(),
        })
    }

    /// Load all sprites from embedded byte slices.
    /// `sprites` is the per-character `SPRITES` constant from the generated
    /// `embedded_assets.rs` module.  Used for the standalone exe where no
    /// external asset directory exists.
    pub fn load_embedded(sprites: &[(&str, &[u8])], manifest: &Manifest, display_width: f64) -> Option<Self> {
        let scale = display_width / manifest.canonical_width.max(1.0);

        let mut images   = HashMap::new();
        let mut mirrored = HashMap::new();
        let mut anchors  = HashMap::new();
        let mut native = HashMap::new();
        let mut native_mirrored = HashMap::new();

        for (name, info) in &manifest.sprites {
            let png_bytes = sprites.iter()
                .find(|(n, _)| *n == name.as_str())
                .map(|(_, b)| *b)?;

            let img = image::load_from_memory(png_bytes).ok()?;
            let (ow, oh) = img.dimensions();
            let native_rgba = img.to_rgba8().into_raw();
            let native_flip = mirror_rgba(&native_rgba, ow, oh);
            let nw = ((ow as f64 * scale).round() as u32).clamp(1, MAX_SPRITE_DIM);
            let nh = ((oh as f64 * scale).round() as u32).clamp(1, MAX_SPRITE_DIM);

            let scaled = img
                .resize_exact(nw, nh, image::imageops::FilterType::Triangle)
                .to_rgba8();

            let anchor = compute_anchor(info.x, info.y, oh as f64, scale, &info.attachment);
            let bgra   = rgba_to_bgra_premul(&scaled);
            let mirror = mirror_bgra(&bgra, nw as usize, nh as usize);

            native.insert(name.clone(), (ow, oh, native_rgba));
            native_mirrored.insert(name.clone(), (ow, oh, native_flip));
            images.insert(name.clone(),   Sprite { bgra,   w: nw as i32, h: nh as i32 });
            mirrored.insert(name.clone(), Sprite { bgra: mirror, w: nw as i32, h: nh as i32 });
            anchors.insert(name.clone(), anchor);
        }

        Some(SpriteAssets {
            images,
            mirrored,
            anchors,
            native,
            native_mirrored,
            cage: RefCell::new(HashMap::new()),
            canonical_width: manifest.canonical_width,
            animations: manifest.animations.clone(),
            surfaces: manifest.surfaces.clone(),
        })
    }

    /// Returns the (optionally mirrored) sprite for `name`.
    pub fn sprite(&self, name: &str, mirror: bool) -> Option<&Sprite> {
        if mirror { self.mirrored.get(name) } else { self.images.get(name) }
    }

    /// Returns the anchor for `name`, or `None` if not loaded.
    pub fn anchor(&self, name: &str) -> Option<Anchor> {
        self.anchors.get(name).copied()
    }

    /// Native PNG size in source pixels.
    pub fn native_size(&self, name: &str) -> (f64, f64) {
        self.native
            .get(name)
            .map(|(w, h, _)| (*w as f64, *h as f64))
            .unwrap_or((512.0, 512.0))
    }

    /// Cage blit source: native PNG scaled once to `dw×dh`, then rotated by a
    /// permitted `angle_id` about the foot. Cache key includes the angle.
    pub fn cage_rgba(
        &self,
        name: &str,
        mirror: bool,
        dw: u32,
        dh: u32,
        angle: crate::vivarium::AngleId,
    ) -> Option<(u32, u32, Vec<u8>, f64, f64)> {
        let key = (name.to_string(), mirror, dw, dh, angle.deg());
        {
            let cache = self.cage.borrow();
            if let Some(v) = cache.get(&key) {
                return Some(v.clone());
            }
        }
        let (sw, sh, src) = if mirror {
            self.native_mirrored.get(name)?
        } else {
            self.native.get(name)?
        };
        let scaled = crate::vivarium::scale_rgba_triangle(src, *sw, *sh, dw, dh);
        let out = crate::vivarium::rotate_rgba_about_foot(&scaled, dw, dh, angle.rad());
        self.cage.borrow_mut().insert(key, out.clone());
        Some(out)
    }

    /// Returns the (w, h) of `name` in display pixels, or `(150, 150)` as
    /// a safe fallback.
    pub fn size(&self, name: &str, mirror: bool) -> (f64, f64) {
        self.sprite(name, mirror)
            .map(|s| (s.w as f64, s.h as f64))
            .unwrap_or((150.0, 150.0))
    }
}

// ---- Helpers ----

/// Build an `Anchor` from raw manifest values.
/// Matches `compute_anchor` in `assets.rs` exactly.
fn compute_anchor(
    x_orig: Option<f64>,
    y_orig: Option<f64>,
    sprite_h_orig: f64,
    scale: f64,
    attachment: &Attachment,
) -> Anchor {
    match attachment {
        Attachment::LineY => {
            let y = (sprite_h_orig - y_orig.unwrap_or(0.0)) * scale;
            Anchor { x: 0.0, y }
        }
        Attachment::LineX => {
            let x = x_orig.unwrap_or(0.0) * scale;
            Anchor { x, y: 0.0 }
        }
        Attachment::Point => {
            let x = x_orig.unwrap_or(0.0) * scale;
            let y = (sprite_h_orig - y_orig.unwrap_or(0.0)) * scale;
            Anchor { x, y }
        }
    }
}

/// Convert RGBA straight-alpha to BGRA pre-multiplied alpha.
fn rgba_to_bgra_premul(img: &image::RgbaImage) -> Vec<u8> {
    img.pixels()
        .flat_map(|p| {
            let a = p[3] as u32;
            [
                (p[2] as u32 * a / 255) as u8, // B
                (p[1] as u32 * a / 255) as u8, // G
                (p[0] as u32 * a / 255) as u8, // R
                p[3],                           // A (unchanged)
            ]
        })
        .collect()
}

fn mirror_rgba(rgba: &[u8], w: u32, h: u32) -> Vec<u8> {
    let w = w as usize;
    let h = h as usize;
    let mut out = vec![0u8; rgba.len()];
    for row in 0..h {
        for col in 0..w {
            let src = (row * w + col) * 4;
            let dst = (row * w + (w - 1 - col)) * 4;
            out[dst..dst + 4].copy_from_slice(&rgba[src..src + 4]);
        }
    }
    out
}

/// Flip a BGRA buffer horizontally (row by row).
fn mirror_bgra(bgra: &[u8], w: usize, h: usize) -> Vec<u8> {
    let mut out = vec![0u8; bgra.len()];
    for row in 0..h {
        for col in 0..w {
            let src = (row * w + col) * 4;
            let dst = (row * w + (w - 1 - col)) * 4;
            out[dst..dst + 4].copy_from_slice(&bgra[src..src + 4]);
        }
    }
    out
}
